version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tovarkaduck-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tovarkaduck
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tovarkaduck
    ports:
      - "5432:5432"
    volumes:
      - tovarkaduck_pg_data:/var/lib/postgresql/data

volumes:
  tovarkaduck_pg_data:
